# =============================================================================
# DEVELOPMENT ENVIRONMENT CONFIGURATION
# =============================================================================

spring:
  application:
    name: portal-user-service-dev
  config:
    activate:
      on-profile: dev

  # =============================================================================
  # DATABASE CONFIGURATION
  # =============================================================================
  driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: false
        # Simple batch optimization
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  # Read/Write DataSource Configuration
  datasource:
    write:
      hikari:
        maximum-pool-size: 50
        minimum-idle: 10
        connection-timeout: 20000
        idle-timeout: 300000
        max-lifetime: 1200000
    read:
      hikari:
        maximum-pool-size: 100
        minimum-idle: 20
        connection-timeout: 10000
        idle-timeout: 600000
        max-lifetime: 1800000



# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
  port: 8080
  compression:
    enabled: true

# =============================================================================
# Security CONFIGURATION
# =============================================================================
app:
  security:
    enabled: false  # Disable security for development or enable it as needed 

# =============================================================================
# AWS CONFIGURATION
# =============================================================================
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    secret-name: 'apps-itt-service-secrets-dev'
    s3:
      bucket-name: 'itt-service-dev-bucket'
# =============================================================================
# EXTERNAL API RATE LIMITING CONFIGURATION
# =============================================================================
external-api:
  rate-limiting:
    enabled: true
    default-config:
      requests-per-hour: 1000
      requests-per-minute: 100
      burst-capacity: 10

# =============================================================================
# API DOCUMENTATION
# =============================================================================
springdoc:
  api-docs:
    path: /api/docs/api-docs
    enabled: true
  swagger-ui:
    path: /api/docs/swagger-ui.html
    enabled: true
  packages-to-scan: com.itt.service

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
  file:
    name: myapp.log
    max-size: 4MB
    max-history: 30
    total-size-cap: 1GB
    path: logs
  level:
    root: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    org.hibernate.SQL: DEBUG
    org.hibernate.type: WARN
    com.zaxxer.hikari: WARN
    com.itt.service.config.security: DEBUG

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================
cache:
  type: caffeine
  refresh-minutes: 10
  ttl-minutes: 10
  redis:
    key-prefix: "lit:"

# =============================================================================
# APPLICATION SPECIFIC CONFIGURATION
# =============================================================================
com:
  itt:
    common:
      open-api:
        enabled: true
        api-version: 1.0.0
        title: portal-user-service-dev
        description: Service API
      token:
        secret-key: 093617ebfa4b9af9700db274ac204ffa34195494d97b9c26c23ad561de817926
        validity: 120

# =============================================================================
# LIT CACHE CONFIGURATION
# =============================================================================
lit:
  cache:
    type: memory
    refresh-minutes: 10
    redis:
      key-prefix: "lit:"
audit:
  config:
    refresh-interval: 4h   # 30m or 4h  Units supported out-of-the-box: ns, ms, s, m, h, d.

